apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: nt548-lab2
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: nt548-lab2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-service
  ports:
    - name: http
      port: 3000
      targetPort: http
